services:

  server:
    build:
      context: ../../server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../../server/.env

  web:
    build:
      context: ../../web
      dockerfile: Dockerfile
      args:
        NEXT_OUTPUT: standalone
    ports:
      - "3000:3000"
    env_file:
      - ../../web/.env.local
    depends_on:
      - server
